name: Test Action
on: push

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        run: |
          import os
          print(os.environ['PATH'])
        shell: python