name: Test Action
on: push
runs-on: ubuntu-latest

jobs:
  my_first_job:
    steps:
      - name: Display the path
        run: |
          import os
          print(os.environ['PATH'])
        shell: python